export const SKILLS = [
  'JavaScript',
  'TypeScript',
  'React',
  'Next.js',
  'Node.js',
  'Python',
  'Java',
  'C++',
  'Go',
  'Rust',
  'SQL',
  'MongoDB',
  'AWS',
  'Docker',
  'Kubernetes',
  'Machine Learning',
  'Data Science',
  'DevOps',
  'Cloud Architecture',
  'System Design',
  'Frontend Development',
  'Backend Development',
  'Mobile Development',
  'UI/UX Design',
  'Testing',
  'Security',
  'Blockchain',
  'AI/ML',
] as const

export const INTERESTS = [
  'Web Development',
  'Mobile Development',
  'Game Development',
  'Artificial Intelligence',
  'Machine Learning',
  'Data Science',
  'Cloud Computing',
  'DevOps',
  'Cybersecurity',
  'Blockchain',
  'IoT',
  'AR/VR',
  'UI/UX Design',
  'Product Management',
  'Agile Methodologies',
  'Open Source',
  'Technical Writing',
  'System Architecture',
  'Database Design',
  'API Development',
  'Microservices',
  'Software Testing',
  'Performance Optimization',
  'Code Review',
  'Team Leadership',
  'Mentoring',
  'Entrepreneurship',
  'Tech Startups',
] as const

export type Skill = typeof SKILLS[number]
export type Interest = typeof INTERESTS[number]
